#!/bin/sh

CHECK_VER_STR="6.0.0"

formatting_files() {
    file="${1}"
    if [ -f $file ]; then
	case "$file" in
	    *.c | *.h | *.hpp | *.cpp )
		clang-format -i ${1}
		git add ${1}
		;;
	    *)
		;;
	esac
    fi
}


_main(){
    echo "Checking version of clang-format."
    VER_STR=`clang-format --version | sed -e "s/clang-format version //" | sed -e "s/-.*//"`
    if [ ${VER_STR:-hoge} != ${CHECK_VER_STR} ] ; then
	echo "Invalid clang-format version"
	exit 1
    fi

    echo "Running clang-format."
    for file in `git diff-index --cached --name-only HEAD`
    do
	DIR_NAME=$(dirname ${file})
	if [ ${DIR_NAME:-xbyak} != xbyak ] ; then
	    formatting_files "${file}"
	else
	    echo "${file} is not indented by clang-format, because it seems to be the original xbyak file."
	fi
    done
}

_main
